-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."emailVerfied"
(
    id integer NOT NULL,
    verfied boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employer
(
    id integer NOT NULL,
    "employerId" integer NOT NULL,
    phone character(15) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."jobPositions"
(
    id integer NOT NULL,
    "jopId" integer NOT NULL,
    "jopName" character varying(200) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."jobSeekers"
(
    id integer NOT NULL,
    "jobSeekersId" integer NOT NULL,
    "nationalityId" character varying(11) NOT NULL,
    "yearOfBirth" date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.system_users
(
    id integer NOT NULL,
    "systemUsersId" integer NOT NULL
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    name character varying(25) NOT NULL,
    surname character varying(30) NOT NULL,
    email text NOT NULL,
    password text NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.employer (id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.system_users (id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public."jobSeekers" (id)
    NOT VALID;


ALTER TABLE public."emailVerfied"
    ADD FOREIGN KEY (id)
    REFERENCES public.employer ("employerId")
    NOT VALID;


ALTER TABLE public."emailVerfied"
    ADD FOREIGN KEY (id)
    REFERENCES public."jobSeekers" ("jobSeekersId")
    NOT VALID;

END;